<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TipsAndSteps.Shared.Contracts</AssemblyName>
    <RootNamespace>TipsAndSteps.Shared.Contracts</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Confluent.SchemaRegistry" Version="2.5.0" />
    <PackageReference Include="Confluent.SchemaRegistry.Serdes.Json" Version="2.5.0" />
  </ItemGroup>
</Project>
