<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>TipsAndSteps.Analytics.API</AssemblyName>
    <RootNamespace>TipsAndSteps.Analytics.API</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Keycloak.AuthServices.Authentication" Version="2.5.0" />
    <PackageReference Include="Keycloak.AuthServices.Authorization" Version="2.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.9.0" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="8.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <ProjectReference Include="..\TipsAndSteps.Analytics.Application\TipsAndSteps.Analytics.Application.csproj" />
    <ProjectReference Include="..\TipsAndSteps.Analytics.Infrastructure\TipsAndSteps.Analytics.Infrastructure.csproj" />
  </ItemGroup>
</Project>
